import React from 'react'

export const Home = () => {
  return (
    <div>
      <h2>Hello World</h2>
      <p>Now we'll take the almighty fan brush. That's crazy. You can create anything that makes you happy. No worries. No cares. Just float and wait for the wind to blow you around. Let's build an almighty mountain. This is your world. Follow the lay of the land. It's most important. In your world you have total and absolute power. Just let this happen. We just let this flow right out of our minds. Just a little indication. If we're going to have animals around we all have to be concerned about them and take care of them. Talent is a pursued interest. That is to say, anything you practice you can do. Maybe there's a happy little waterfall happening over here. Be careful. You can always add more - but you can't take it away. Let's put some happy little clouds in our world. Tree trunks grow however makes them happy. Steve wants reflections, so let's give him reflections. These little son of a guns hide in your brush and you just have to push them out. The secret to doing anything is believing that you can do it. Anything that you believe you can do strong enough, you can do. Anything. As long as you believe</p>

      <p>You have freedom here. The only guide is your heart. Exercising the imagination, experimenting with talents, being creative; these things, to me, are truly the windows to your soul. I'm gonna add just a tiny little amount of Prussian Blue. That's what painting is all about. It should make you feel good when you paint. Just let this happen. We just let this flow right out of our minds. We'll throw some happy little limbs on this tree. Follow the lay of the land. It's most important. In your world you have total and absolute power. Just let this happen. We just let this flow right out of our minds. Just a little indication. If we're going to have animals around we all have to be concerned about them and take care of them. Talent is a pursued interest. That is to say, anything you practice you can do. Maybe there's a happy little waterfall happening over here. Be careful. You can always add more - but you can't take it away. Let's put some happy little clouds in our world. Tree trunks grow however makes them happy. Steve wants reflections, so let's give him reflections. These little son of a guns hide in your brush and you just have to push them out. The secret to doing anything is believing that you can do it. Anything that you believe you can do strong enough, you can do. Anything. As long as you believe</p>
      
      <p>Didn't you know you had that much power? You can move mountains. You can do anything. It's beautiful - and we haven't even done anything to it yet. Let your imagination just wonder around when you're doing these things. Automatically, all of these beautiful, beautiful things will happen. What the devil. Follow the lay of the land. It's most important. In your world you have total and absolute power. Just let this happen. We just let this flow right out of our minds. Just a little indication. If we're going to have animals around we all have to be concerned about them and take care of them. Talent is a pursued interest. That is to say, anything you practice you can do. Maybe there's a happy little waterfall happening over here. Be careful. You can always add more - but you can't take it away. Let's put some happy little clouds in our world. Tree trunks grow however makes them happy. Steve wants reflections, so let's give him reflections. These little son of a guns hide in your brush and you just have to push them out. The secret to doing anything is believing that you can do it. Anything that you believe you can do strong enough, you can do. Anything. As long as you believe</p>
    </div>
  );
}